### ISSUE TITLE
Effect Speed Issue

### ISSUE THREAD

**Issue by techmarktm** [timmo001/ESP8266-MQTT-JSON-Lights#10]
# Description
Hello Timmo!

I recently setup your solution for MQTT-JSON lights to my HASS project.

I noticed that the automation for the input slider to control the effect speed wasn't working properly, probably because of the new template for automations adopted by Home Assistant.

After a few minutes trying to debbug it, I finally made it work, mainly for the new implementation of automations (throught automations.yaml file).

## Suggested Actions

Considering that "automation: !include automations.yaml" it's included in configuration.yaml,

Add this to automations.yaml file:

```
- id: '###any id here###'
  alias: Led Effect Speed
  trigger:
  - entity_id: input_number.led_effect_speed
    platform: state
  condition: []
  action:
  - data:
      payload_template: '{"speed":{{ states(''input_number.led_effect_speed'') | int }}}'
      topic: light/led/set
    service: mqtt.publish
```

## Additional

It can be done through the build-in automation editor on HASS.

I hope that it helps, and congrats for your project, very useful and well coded ;D
