### ISSUE TITLE
light crashes Home Assistant lovelace UI

### ISSUE THREAD

**Issue by prankousky** [timmo001/ESP8266-MQTT-JSON-Lights#17]
Hi,

I am using `ESP8266-MQTT-JSON-Lights` with a `nodeMCU` and `WS2812` and integrated it into Home Assistant as described [here](https://github.com/timmo001/ESP8266-MQTT-JSON-Lights).

 I can toggle this light just fine, and use it in automations, scripts, and scenes; but when I open the popup box *within Home Assistant* that lets you pick and change color, brightness, effects, lovelace  crashes. On desktop, I'll eventually get a notification that a script on this website is slowing down the browser (options wait or stop script; when I wait the dialog will pop up later, it will not work at all); on mobile browser, nothing will work and I'll have to manually quit the browser and open it again to access Home Assistant again.

I am using Firefox on both desktop and mobile, but I have also tried the Home Assistant android app as well as other browsers (even resorted to installing Chrome on my Android), but the problem occurs there as well.

This entire code block is based on your example, and it should work like this, right? However, I also have some ESPHome controlled LED strips, which work fine; I used to have a Tasmota one as well, that also worked without any trouble. Only this one will freeze my lovelace. 
(I use the very same LED strips, nodeMCU modules, and power supplies for this project, ESPHome, and -when it was still in use- Tasmota; so this should not be a hardware problem, especially because the light itself works fine and is controllable; only opening the popup box containing its settings will mess things up)

I have tried deleting some effects from the effect_list (assuming those might just have been too many), but that didn't work; also, it'd seem pretty strange to me if a list could break Home Assistant just like that.

Is something wrong with my configuration? Or do you have an idea how I can fix this? I cross-posted this [in the Home Assistant community](https://community.home-assistant.io/t/mqtt-light-crashes-lovelace/137060).

Thank you for your support :)

```
light:
  platform: mqtt
  schema: json
  name: 'SZ LED Seite'
  state_topic: 'light/led'
  command_topic: 'light/led/set'
  availability_topic: 'light/led/LWT'
  payload_available: 'Online'
  payload_not_available: 'Offline'
  effect: true
  effect_list:
    - static
    - blink
    - breath
    - color wipe
    - color wipe inverted
    - color wipe reverse
    - color wipe reverse inverted
    - color wipe random
    - random color
    - single dynamic
    - multi dynamic
    - rainbow
    - rainbow cycle
    - scan
    - dual scan
    - fade
    - theater chase
    - theater chase rainbow
    - running lights
    - twinkle
    - twinkle random
    - twinkle fade
    - twinkle fade random
    - sparkle
    - flash sparkle
    - hyper sparkle
    - strobe
    - strobe rainbow
    - multi strobe
    - blink rainbow
    - chase white
    - chase color
    - chase random
    - chase rainbow
    - chase flash
    - chase random
    - chase rainbow white
    - chase blackout
    - chase blackout rainbow
    - color sweep random
    - running color
    - running red blue
    - running random
    - larson scanner
    - comet
    - fireworks
    - fireworks random
    - merry christmas
    - fire flicker
    - fire flicker soft
    - fire flicker intense
    - circus combustus
    - halloween
    - bicolor chase
    - tricolor chase
    - icu
  brightness: true
  rgb: true
  optimistic: false
  qos: 0

input_number:
  led_effect_speed:
    name: 'LED Effect Speed'
    initial: 50 # This is the default speed
    mode: slider
    min: 10  # ######################################
    max: 500 # Feel Free to adjust these as you like
    step: 5 # ######################################

automation:
  - id: 'led8266'
    alias: "[Licht] LED8266 Speed"
    action:
      - alias: Set LED Lights Effect Speed
        service: mqtt.publish
        data_template:
          topic: light/led/set
          payload: '{"speed":{{ trigger.to_state.state | int }}}'
    trigger:
      - platform: state
        entity_id: input_number.led_effect_speed
```
